// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwlhsinonoxhmupuzdjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bGhzaW5vbm94aG11cHV6ZGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTUzMDEsImV4cCI6MjA3MjE5MTMwMX0.UPH98xt2a5K0vxRCbyvr2fZWc0hQWEf1TGWKCiCGxrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});